config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :activities

  resources :projects

  devise_for :users, controllers: { sessions: "users/sessions",
              registrations: "users/registrations",
              unlocks: "users/unlocks",passwords: "users/passwords",
              confirmations: "users/confirmations" }

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :project

   scope :list, -> { where.not(ended_at: nil)}


  def self.proceso
    Activity.find_by_ended_at(nil)
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :activities, dependent: :destroy
  validates :name, presence: true, uniqueness: true, length: { minimum: 5 }

  def total
    activities.sum(:total)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :projects
  has_many :activities
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

before_action :authenticate_user!
 def index
  @activities=Activity.list
  @proceso= Activity.proceso || Activity.new

 end

 def new
  @activity= Activity.new
 end

 def create
   @activity= Activity.create(parametros)
   @activity.started_at= Time.new
   @activity.save
   redirect_to activities_path
 end

 def update
    @activity= Activity.update(params[:id],parametros)
    @activity.ended_at= Time.new
    @activity.total= (@activity.ended_at-@activity.started_at).to_i
    @activity.save
    redirect_to activities_path

 end

 private

 def parametros
   params.require(:activity).permit(:descripcion, :project_id)
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   def after_sign_in_path_for(resource)
     activities_path
  end

  before_action :set_locale

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
      @projects=Project.all

  end

  def new
    @project=Project.new
  end

  def create
    @project= Project.create(parametros)
    @project.user_id= current_user.id
    @project.save
  end

  def edit
     @project= Project.find(params[:id])
  end

  def update
     @project= Project.update(params[:id],parametros)
  end


  def destroy
     @project=Project.destroy(params[:id])
     redirect_to projects_path
  end

  private

  def parametros

    params.require(:project).permit(:name)
  end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

 #POST /resource/sign_in
   def create
      super
   end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected



  # You can put the params you want to permit in the empty array.
   def configure_sign_in_params
    devise_parameter_sanitizer.for(:sign_in) << :attribute
   end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/activities/index.html.erb
<div class="dashboard main">
  <div class="container">
    <div class="row">
      <div class="col-sm-12 activity-form">


        <%= form_for @proceso do |f| %>

          <div class="form-group col-sm-3">
          <%= f.collection_select(:project_id, Project.all, :id, :name,{:prompt => false},{class:"form-control"})  %>
          </div>
          <div class="form-group col-sm-8">
            <%= f.text_field :descripcion, class:"form-control", placeholder:"¿En qué estás trabajando?" %>
          </div>
          <div class="col-sm-1">

            <% if @proceso.started_at==nil %>
                <%= f.submit "Start", class:"btn btn-success" %>
             <% else %>
                 <%= f.submit "Stop", class:"btn btn-danger" %>
            <% end %>
          </div>
         <% end %>
      </div>
    </div>


    <div class="row">
      <table class="table activities-list">
        <thead>
          <tr>
            <th>Project</th>
            <th>Description</th>
            <th class="text-center">Time</th>
          </tr>
        </thead>
        <tbody>

          <% @activities.each do |a| %>
          <tr>
            <td><%= a.project.name %></td>
            <td> <%= a.descripcion %></td>
            <td class="text-center"><%= (a.ended_at-a.started_at).to_i %> segundos</td>
          </tr>
          <% end %>


        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div class="home">
    <div class="container">
      <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
          <h1><span class="glyphicon glyphicon-time"></span> The Time Tracking App</h1>
          <p class="subtitle">Time tracking has never been this easy ... until now!</p>
          <div class="call-to-action">
             <%= link_to 'Sign up now',new_user_registration_path, class:"btn btn-default btn-lg"%>
             <%= link_to '... or Log in', new_user_session_path, class:'btn btn-lg' %>

          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container cite">
    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
        <h2>Our customers love us!</h2>
        <p>Or they will ... when we get them.</p>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TimeApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
       <%= link_to 'TimeApp', ' # ', class:"navbar-brand"%>
      <% else %>
       <%= link_to 'TimeApp', root_path , class:"navbar-brand"%>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
         <% if user_signed_in? %>

           <li <% if current_page?(activities_path) %>class="active"
            <%end%>>
             <%= link_to "Dashboard",activities_path %>
           </li>

         <li  <% if current_page?(projects_path) %> class="active" <%end%>><%= link_to "Project",projects_path, id:"project" %></li>

         <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>

          <li> <%= link_to 'Logout',destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign Up',new_user_registration_path %></li>
          <li><%= link_to 'Log in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>




<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project ,remote: true do |f| %>
    <div class="modal-body">
    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.button "Create Project",class:"btn btn-success",data: {disable_with: "<i class='fa fa-circle-o-notch fa-spin '></i>"}%>
  </div>
<% end %>

app/views/projects/_modalnew.html.erb
  <div id="project-content-modal" class="modal fade">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">
            <span aria-hidden="true">×</span><span class="sr-only">Close</span>
          </button>
          <h4 class="modal-title">New Project</h4>
        </div>

          <%= render 'form' %>


      </div><!-- .modal-content -->
    </div><!-- .modal-dialog -->
  </div>

app/views/projects/create.js.erb
<%  if @project.errors.any? %>


alert('<%= @project.errors.full_messages[0] %>');

<% else%>

window.location.href = '<%= projects_path %>'

<%end %>

app/views/projects/edit.js.erb
$('<%= j render 'modalnew' %>').modal()

app/views/projects/index.html.erb
  <div class="projects main">
    <div class="container">
      <div class="row text-right">
        <%= link_to 'New Project', new_project_path ,class:'btn btn-primary', remote: true %>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <table class="table projects-list">
            <thead>
              <tr>
                <th>Name</th>
                <th>Time</th>
                <th></th>
              </tr>
            </thead>
            <tbody>

              <% @projects.each do |p| %>
               <tr>
                <td><%= p.name %></td>
                <td><%= p.total %> Segundos</td>

                <td class="text-right">
                  <%= link_to ('<span class="glyphicon glyphicon-edit"></span>Editar').html_safe, edit_project_path(p), remote: true %>
                  <%= link_to ('<span class="glyphicon glyphicon-remove"></span>Eliminar').html_safe, project_path(p), method: :delete , data:{confirm:"Deseas eliminar el Item"} %>
                </td>
              </tr>

               <% end %>

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/projects/new.js.erb
$('<%= j render 'modalnew' %>').modal()

app/views/projects/update.js.erb
<%  if @project.errors.any? %>
  alert('<%= @project.errors.full_messages[0] %>');
<% else%>
  window.location.href = '<%= projects_path %>'
<%end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>